import { Platform, StyleSheet } from "react-native";

import { BottomTabInset, Fonts, Radius, Spacing } from "@/constants/theme";

export const Colors = {
  background: "#0C0C0E",
  card: "#1E1E21",
  surface: "#17120E",
  surfaceHigh: "#271E16",
  border: "#3E332B",
  borderSoft: "#554336",
  text: "#E4E4E7",
  warmText: "#F2DFD3",
  muted: "#A1A1AA",
  body: "#DBC2B0",
  primary: "#D97706",
  primaryLight: "#FFB77D",
  danger: "#FFB4AB",
  buttonText: "#0C0C0E",
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.three,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(85, 67, 54, 0.45)",
    backgroundColor: Colors.background,
    gap: Spacing.two,
  },
  headerTop: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: Radius.full,
  },
  headerTitle: {
    flex: 1,
    color: Colors.primaryLight,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
    textAlign: "center",
  },
  progressLabel: {
    color: Colors.body,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  readingProgress: {
    minHeight: 58,
    borderColor: "rgba(255, 183, 125, 0.22)",
    backgroundColor: Colors.card,
  },
  progressTrack: {
    height: 5,
    borderRadius: Radius.full,
    overflow: "hidden",
    backgroundColor: Colors.surfaceHigh,
  },
  progressFill: {
    height: "100%",
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryLight,
  },
  content: {
    width: "100%",
    maxWidth: 780,
    alignSelf: "center",
    padding: Spacing.three,
    paddingBottom: BottomTabInset + Spacing.five,
    gap: Spacing.four,
  },
  lessonActions: {
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    gap: Spacing.two,
    paddingTop: Spacing.two,
  },
  metaWrap: {
    gap: Spacing.three,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  chip: {
    minHeight: 30,
    paddingHorizontal: Spacing.three,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 183, 125, 0.22)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.surfaceHigh,
  },
  chipMuted: {
    borderColor: "transparent",
  },
  chipDanger: {
    borderColor: "rgba(255, 180, 171, 0.25)",
    backgroundColor: "rgba(147, 0, 10, 0.22)",
  },
  chipText: {
    color: Colors.primaryLight,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900",
  },
  chipTextMuted: {
    color: Colors.body,
  },
  chipTextDanger: {
    color: Colors.danger,
  },
  title: {
    color: Colors.warmText,
    fontFamily: Fonts.serif,
    fontSize: 31,
    lineHeight: 39,
    fontWeight: "900",
  },
  titleRule: {
    width: 52,
    height: 2,
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryLight,
  },
  heroImage: {
    width: "100%",
    height: Platform.select({ web: 320, default: 210 }),
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
    backgroundColor: Colors.card,
  },
  section: {
    gap: Spacing.two,
  },
  sectionTitle: {
    color: Colors.primaryLight,
    fontFamily: Fonts.serif,
    fontSize: 25,
    lineHeight: 32,
    fontWeight: "900",
  },
  paragraph: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  bodyText: {
    color: Colors.body,
    fontSize: 16,
    lineHeight: 25,
    fontWeight: "500",
  },
  italicText: {
    fontStyle: "italic",
  },
  conceptText: {
    color: Colors.primaryLight,
    fontSize: 16,
    lineHeight: 25,
    fontWeight: "900",
    textDecorationLine: "underline",
    textDecorationStyle: "dashed",
  },
  quote: {
    marginVertical: Spacing.two,
    paddingLeft: Spacing.three,
    borderLeftWidth: 3,
    borderLeftColor: Colors.primaryLight,
  },
  quoteText: {
    color: Colors.warmText,
    fontSize: 17,
    lineHeight: 26,
    fontStyle: "italic",
    fontWeight: "700",
  },
  conceptPanel: {
    padding: Spacing.three,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 183, 125, 0.22)",
    gap: Spacing.three,
    backgroundColor: Colors.card,
  },
  panelLabel: {
    color: Colors.primaryLight,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  conceptGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  conceptChip: {
    minHeight: 38,
    paddingHorizontal: Spacing.three,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 183, 125, 0.35)",
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    backgroundColor: Colors.surfaceHigh,
  },
  conceptChipText: {
    color: Colors.primaryLight,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
    paddingBottom: BottomTabInset + Spacing.three,
    borderTopWidth: 1,
    borderTopColor: "rgba(85, 67, 54, 0.45)",
    backgroundColor: Colors.background,
  },
  bottomInner: {
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    gap: Spacing.two,
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: Radius.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    backgroundColor: Colors.primaryLight,
  },
  primaryButtonText: {
    color: Colors.buttonText,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
  },
  secondaryButton: {
    minHeight: 50,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    backgroundColor: Colors.surfaceHigh,
  },
  secondaryButtonText: {
    color: Colors.body,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    padding: Spacing.three,
    backgroundColor: "rgba(0, 0, 0, 0.66)",
  },
  modalCard: {
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
    padding: Spacing.four,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: "rgba(255, 183, 125, 0.28)",
    gap: Spacing.three,
    backgroundColor: Colors.card,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  modalTitle: {
    flex: 1,
    color: Colors.primaryLight,
    fontFamily: Fonts.serif,
    fontSize: 23,
    lineHeight: 30,
    fontWeight: "900",
  },
  modalBody: {
    color: Colors.body,
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "600",
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
});
