import { StyleSheet } from "react-native";

import { BottomTabInset, Fonts, Radius, Spacing } from "@/constants/theme";

export const Colors = {
  primary: "#D97706",
  primaryLight: "#FFB77D",
  secondaryText: "#E4E4E7",
  mutedText: "#A1A1AA",
  background: "#0C0C0E",
  surface: "#161618",
  card: "#1E1E21",
  cardSoft: "#231A13",
  border: "#3A3028",
  borderMuted: "#2F2A24",
  buttonText: "#0C0C0E",
  danger: "#F87171",
  success: "#22C55E",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.one,
    paddingBottom: Spacing.two,
    gap: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderMuted,
    backgroundColor: Colors.background,
  },
  headerRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitleBlock: {
    alignItems: "center",
    gap: Spacing.half,
  },
  headerTitle: {
    color: Colors.primaryLight,
    fontFamily: Fonts.serif,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  headerCount: {
    color: Colors.secondaryText,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  progressTrack: {
    height: 5,
    borderRadius: Radius.full,
    overflow: "hidden",
    backgroundColor: Colors.borderMuted,
  },
  progressFill: {
    height: "100%",
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryLight,
  },
  content: {
    flexGrow: 1,
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    padding: Spacing.three,
    paddingBottom: BottomTabInset + Spacing.five,
    gap: Spacing.three,
  },
  animatedCardWrap: {
    minHeight: 520,
  },
  lessonCard: {
    minHeight: 520,
    overflow: "hidden",
    padding: Spacing.four,
    justifyContent: "space-between",
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  cardImage: {
    ...StyleSheet.absoluteFill,
    opacity: 0.18,
  },
  cardScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(12,12,14,0.56)",
  },
  cardMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  softBadge: {
    backgroundColor: "#2B2118",
    borderWidth: 1,
    borderColor: "#5A3B1C",
  },
  primaryBadge: {
    backgroundColor: Colors.primaryLight,
  },
  cardBody: {
    gap: Spacing.three,
  },
  cardTitle: {
    color: Colors.secondaryText,
    fontFamily: Fonts.serif,
    fontSize: 25,
    lineHeight: 32,
    fontWeight: "800",
  },
  titleRule: {
    width: 58,
    height: 4,
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryLight,
  },
  cardText: {
    color: Colors.secondaryText,
    fontSize: 16,
    lineHeight: 25,
    fontWeight: "600",
  },
  conceptBlock: {
    gap: Spacing.two,
  },
  metaLabel: {
    color: Colors.mutedText,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  conceptChip: {
    alignSelf: "flex-start",
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: "#7C4A19",
    backgroundColor: "#322416",
  },
  conceptText: {
    color: Colors.primaryLight,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  voteCard: {
    minHeight: 520,
    padding: Spacing.three,
    gap: Spacing.three,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  voteTitleBlock: {
    alignItems: "center",
    gap: Spacing.two,
  },
  voteTitle: {
    color: Colors.secondaryText,
    fontFamily: Fonts.serif,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: "800",
  },
  voteImage: {
    width: "100%",
    height: 190,
    borderRadius: Radius.md,
    backgroundColor: Colors.cardSoft,
  },
  voteList: {
    gap: Spacing.two,
  },
  voteOption: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    padding: Spacing.three,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.borderMuted,
    backgroundColor: Colors.cardSoft,
  },
  voteOptionSelected: {
    borderWidth: 2,
    borderColor: Colors.primaryLight,
    backgroundColor: "#302217",
  },
  voteOptionSubmitted: {
    borderColor: Colors.success,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: Radius.full,
    borderWidth: 2,
    borderColor: Colors.mutedText,
    alignItems: "center",
    justifyContent: "center",
  },
  radioSelected: {
    borderColor: Colors.primaryLight,
  },
  radioInner: {
    width: 9,
    height: 9,
    borderRadius: Radius.full,
  },
  radioInnerSelected: {
    backgroundColor: Colors.primaryLight,
  },
  voteOptionCopy: {
    flex: 1,
    gap: Spacing.half,
  },
  voteOptionText: {
    color: Colors.mutedText,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  voteOptionTextSelected: {
    color: Colors.secondaryText,
  },
  votePercent: {
    color: Colors.primaryLight,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  inlineResult: {
    gap: Spacing.three,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  inlineResultTitle: {
    color: Colors.secondaryText,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "900",
  },
  inlineResultPercent: {
    color: Colors.primaryLight,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
  },
  resultCard: {
    gap: Spacing.four,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  resultHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.three,
  },
  resultTitle: {
    color: Colors.secondaryText,
    fontFamily: Fonts.serif,
    fontSize: 26,
    lineHeight: 34,
    fontWeight: "800",
  },
  explanationBox: {
    padding: Spacing.three,
    borderLeftWidth: 2,
    borderLeftColor: Colors.primaryLight,
    borderRadius: Radius.sm,
    backgroundColor: Colors.cardSoft,
  },
  explanationText: {
    color: Colors.secondaryText,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  navigationRow: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  outlineAction: {
    flex: 1,
    minHeight: 54,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.one,
  },
  outlineActionText: {
    color: Colors.secondaryText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  primaryAction: {
    flex: 1.2,
    minHeight: 54,
    borderRadius: Radius.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    backgroundColor: Colors.primaryLight,
  },
  primaryActionText: {
    color: Colors.buttonText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  disabledAction: {
    opacity: 0.45,
  },
  actionStack: {
    gap: Spacing.two,
  },
  stateBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.three,
    padding: Spacing.four,
  },
  stateTitle: {
    color: Colors.secondaryText,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
  },
  stateText: {
    maxWidth: 300,
    color: Colors.mutedText,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
});
