export enum ActivityType {
  LEARN_LESSON = "LEARN_LESSON",
  DO_QUIZ = "DO_QUIZ",
  DECIDE_STORY = "DECIDE_STORY",
  DO_SHORT_LESSON = "DO_SHORT_LESSON",
  PLAY_MINI_GAME = "PLAY_MINI_GAME",
  WRITE_REFLECTION = "WRITE_REFLECTION",
  LOGIN = "LOGIN",
}

export enum TargetType {
  LESSON = "LESSON",
  SHORT_LESSON = "SHORT_LESSON",
  STORY = "STORY",
  TOPIC = "TOPIC",
  MINDMAP_NODE = "MINDMAP_NODE",
  QUIZ = "QUIZ",
  MINI_GAME = "MINI_GAME",
  REFLECTION = "REFLECTION",
}
