import { StyleSheet } from "react-native";

import { BottomTabInset, Fonts, Radius, Spacing } from "@/constants/theme";

export const QuizColors = {
  primary: "#D97706",
  primaryLight: "#FFB77D",
  text: "#E4E4E7",
  muted: "#A1A1AA",
  background: "#0C0C0E",
  card: "#1E1E21",
  cardSoft: "#17120E",
  border: "#3A3028",
  success: "#22C55E",
  danger: "#EF4444",
  warning: "#F59E0B",
  buttonText: "#0C0C0E",
  locked: "#52525B",
};

export const quizStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: QuizColors.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: QuizColors.background,
  },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    padding: Spacing.three,
    paddingBottom: BottomTabInset + Spacing.five,
    gap: Spacing.three,
  },
  header: {
    minHeight: 58,
    paddingHorizontal: Spacing.three,
    borderBottomWidth: 1,
    borderBottomColor: "#27272A",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: QuizColors.background,
  },
  headerSide: {
    minWidth: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  brand: {
    color: QuizColors.primaryLight,
    fontFamily: Fonts.serif,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
  },
  timerPill: {
    minHeight: 34,
    paddingHorizontal: Spacing.two,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: "#5A3B1C",
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.one,
    backgroundColor: "#1B1510",
  },
  timerText: {
    color: QuizColors.primaryLight,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  title: {
    color: QuizColors.text,
    fontFamily: Fonts.serif,
    fontSize: 26,
    lineHeight: 34,
    fontWeight: "900",
  },
  subtitle: {
    color: QuizColors.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  statCard: {
    width: "48%",
    minHeight: 82,
    padding: Spacing.three,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: QuizColors.border,
    backgroundColor: QuizColors.card,
  },
  statLabel: {
    color: QuizColors.muted,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  statValue: {
    color: QuizColors.primaryLight,
    fontFamily: Fonts.serif,
    fontSize: 25,
    lineHeight: 32,
    fontWeight: "900",
  },
  searchBox: {
    minHeight: 46,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: "#27272A",
    paddingHorizontal: Spacing.three,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.two,
    backgroundColor: QuizColors.card,
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    padding: 0,
    color: QuizColors.text,
    fontFamily: Fonts.body,
    fontSize: 14,
    fontWeight: "700",
  },
  chipRow: {
    gap: Spacing.two,
    paddingRight: Spacing.three,
  },
  chip: {
    minHeight: 36,
    paddingHorizontal: Spacing.three,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: QuizColors.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: QuizColors.card,
  },
  chipActive: {
    borderColor: QuizColors.primary,
    backgroundColor: QuizColors.primary,
  },
  chipText: {
    color: QuizColors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  chipTextActive: {
    color: QuizColors.buttonText,
  },
  quizCard: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: QuizColors.border,
    overflow: "hidden",
    backgroundColor: QuizColors.card,
  },
  quizImage: {
    width: "100%",
    height: 148,
    opacity: 0.74,
  },
  quizBody: {
    padding: Spacing.three,
    gap: Spacing.two,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.two,
  },
  topic: {
    flex: 1,
    color: QuizColors.primaryLight,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  status: {
    color: QuizColors.muted,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "900",
  },
  cardTitle: {
    color: QuizColors.text,
    fontFamily: Fonts.serif,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "900",
  },
  cardText: {
    color: QuizColors.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
  },
  metaText: {
    color: QuizColors.muted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  progressTrack: {
    height: 5,
    borderRadius: Radius.full,
    overflow: "hidden",
    backgroundColor: "#27272A",
  },
  progressFill: {
    height: "100%",
    borderRadius: Radius.full,
    backgroundColor: QuizColors.primaryLight,
  },
  primaryButton: {
    minHeight: 46,
    borderRadius: Radius.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
    backgroundColor: QuizColors.primaryLight,
  },
  primaryButtonText: {
    color: QuizColors.buttonText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  outlineButton: {
    minHeight: 46,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: QuizColors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.two,
  },
  outlineButtonText: {
    color: QuizColors.text,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  disabled: {
    opacity: 0.45,
  },
  questionCard: {
    padding: Spacing.three,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: QuizColors.border,
    gap: Spacing.three,
    backgroundColor: QuizColors.card,
  },
  questionTitle: {
    color: QuizColors.text,
    fontFamily: Fonts.serif,
    fontSize: 23,
    lineHeight: 30,
    fontWeight: "900",
  },
  contextBox: {
    padding: Spacing.three,
    borderLeftWidth: 3,
    borderLeftColor: QuizColors.primary,
    borderRadius: Radius.sm,
    backgroundColor: "#231A13",
  },
  option: {
    minHeight: 62,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: QuizColors.border,
    padding: Spacing.three,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    backgroundColor: QuizColors.card,
  },
  optionSelected: {
    borderWidth: 2,
    borderColor: QuizColors.primaryLight,
    backgroundColor: "#2B2118",
  },
  optionCorrect: {
    borderColor: QuizColors.success,
    backgroundColor: "#102016",
  },
  optionWrong: {
    borderColor: QuizColors.danger,
    backgroundColor: "#241313",
  },
  optionBadge: {
    width: 34,
    height: 34,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: QuizColors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  optionText: {
    flex: 1,
    color: QuizColors.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
  },
  explanation: {
    padding: Spacing.three,
    borderRadius: Radius.md,
    borderLeftWidth: 3,
    borderLeftColor: QuizColors.primaryLight,
    gap: Spacing.two,
    backgroundColor: "#231A13",
  },
  explanationTitle: {
    color: QuizColors.primaryLight,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  resultHero: {
    alignItems: "center",
    gap: Spacing.three,
    paddingVertical: Spacing.four,
  },
  scoreRing: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 12,
    borderColor: QuizColors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1B1510",
  },
  scoreText: {
    color: QuizColors.primaryLight,
    fontFamily: Fonts.serif,
    fontSize: 38,
    lineHeight: 46,
    fontWeight: "900",
  },
  stateBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: Spacing.four,
    gap: Spacing.three,
  },
  stateCard: {
    width: "100%",
    maxWidth: 420,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: QuizColors.border,
    padding: Spacing.four,
    alignItems: "center",
    gap: Spacing.three,
    backgroundColor: QuizColors.card,
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
});
