export enum ActivityType {
  LEARN_LESSON = "LEARN_LESSON",
  DO_QUIZ = "DO_QUIZ",
  WRITE_REFLECTION = "WRITE_REFLECTION",
  CREATE_DEBATE = "CREATE_DEBATE",
  POST_ARGUMENT = "POST_ARGUMENT",
  DECIDE_STORY = "DECIDE_STORY",
  DO_SHORT_LESSON = "DO_SHORT_LESSON",
  CHAT_AI = "CHAT_AI",
}

export enum TargetType {
  LESSON = "LESSON",
  SHORT_LESSON = "SHORT_LESSON",
  STORY = "STORY",
  DEBATE = "DEBATE",
  ARGUMENT = "ARGUMENT",
  TOPIC = "TOPIC",
  MINDMAP_NODE = "MINDMAP_NODE",
  REFLECTION = "REFLECTION",
  AI_CHAT = "AI_CHAT",
  SCENARIO = "SCENARIO",
  QUIZ = "QUIZ",
  MINI_GAME = "MINI_GAME",
}
